In [4]:
import numpy as np

In [5]:
# Q1
a = np.arange(0,6)
print(a)
print(a.dtype)

[0 1 2 3 4 5]
int32


In [6]:
# Q2:
a2 = np.arange(12 , dtype=float)
a2.dtype == np.float64

True

In [7]:
# Q3
a3 =  np.array([1+2j, 3+4j, 5+6j])
a3

array([1.+2.j, 3.+4.j, 5.+6.j])

In [8]:
# Q4
a4 = np.array([1, 2, 3, 4])
arr  = a4.astype(np.float32)
print(arr.dtype)

float32


In [9]:
# Q5
a5 = np.array([5.6777777, 7.77777777 , 1.7777777722] ,dtype = np.float64)
arr = a5.astype(np.float32)
arr

array([5.677778 , 7.7777777, 1.7777778], dtype=float32)

In [10]:
# Q6
def array_attributes(arr):
    return arr.shape , arr.size , arr.dtype
arr = np.array([[1, 2], [3, 4]])
array_attributes(arr)

((2, 2), 4, dtype('int32'))

In [11]:
# Q7
def array_dimension(arr):
    return arr.ndim
arr = np.array([[1, 2], [3, 4]])
array_dimension(arr)

2

In [12]:
# Q8:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3])
print(item_size_info(arr))

(4, 12)


In [13]:
# Q9:
#  Strides in NumPy tell you how many bytes to step in each dimension when traversing the array.
def array_strides(arr):
    return arr.strides
arr=np.array([[1,2] , [4,7]])
array_strides(arr)

(8, 4)

In [14]:
# Q10:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
arr = np.array([[1, 2], [3, 4]])
print(shape_stride_relationship(arr))

((2, 2), (8, 4))


In [15]:
# Q11:
def create_zeros_array(n):
    return np.zeros(n)
print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [16]:
# Q12
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
print(create_ones_matrix(2, 3))

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# Q13
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
print(generate_range_array(0, 10, 2))

[0 2 4 6 8]


In [18]:
# Q14
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
print(generate_linear_space(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [19]:
# Q15
def create_identity_matrix(n):
    return np.eye(n)
print(create_identity_matrix(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# Q16
def list_to_numpy_array(py_list):
    return np.array(py_list)
print(list_to_numpy_array([1, 2, 3, 4]))

[1 2 3 4]


In [21]:
# Q17
arr = np.array([10, 20, 30, 40])
newarr = arr.view()
print(arr)
print(newarr)

[10 20 30 40]
[10 20 30 40]


In [22]:
# Q18
def concatarray(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(concatarray(a, b, axis=0))  # Vertical concat
print(concatarray(a, b, axis=1))  # Horizontal concat

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [23]:
# Q19
def concathor(a, b):
    if a.shape[0] != b.shape[0]:
        raise ValueError("Arrays must have the same number of rows to concatenate horizontally.")
    return np.concatenate((a, b), axis=1)
a = np.array([[1], [2], [3]])
b = np.array([[10, 20], [30, 40], [50, 60]])
print(concathor(a, b))

[[ 1 10 20]
 [ 2 30 40]
 [ 3 50 60]]


In [24]:
# Q20
def vertical_stack(array_list):
    return np.vstack(array_list)
arrays = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
print(vertical_stack(arrays))

[[1 2]
 [3 4]
 [5 6]]


In [25]:
# Q21
def genarr(start,stop,step):
    return np.arange(start,stop+1,step)
print(genarr(1,10,2))

[1 3 5 7 9]


In [26]:
# Q22
arr = np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [27]:
# Q23
spacedarr = np.logspace(0, 3, 5)  # log10(1) = 0, log10(1000) = 3
spacedarr

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [28]:
# Q24
import pandas as pd
def create_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    df = pd.DataFrame(data, columns=['A', 'B', 'C'])
    return df
print(create_dataframe())

    A   B   C
0  67  79  39
1  71  69  42
2   1  50  67
3  82  85  82
4  90  51  17


In [29]:
# Q25

In [30]:
# Q26
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [31]:
# Q27
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
element = arr[1, 2]
print(element)

6


In [32]:
# Q28
arr = np.array([1, 6, 3, 8, 5, 10])
greaterthan5 = arr[arr > 5]
print(greaterthan5)

[ 6  8 10]


In [33]:
# Q29
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
new = arr[2:6]
print(new)

[2 3 4 5]


In [34]:
# Q30
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
new = arr[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2
print(new)

[[2 3]
 [5 6]]


In [35]:
# Q31
arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
# Extract elements at positions (0,1) i.e 20, (1,2) i.e 60, and (2,0) i.e 70
row_indices = [0, 1, 2] # You want to access row 0, then row 1, then row 2
col_indices = [1, 2, 0] # From each of those rows, you want to access column 1, 2, and 0, respectively
ans = arr[row_indices, col_indices]
print(ans)

[20 60 70]


In [36]:
arr = np.array([4, 9, 2, 12, 5, 8])
threshold = 5
ans = arr[arr > threshold]
print(ans)

[ 9 12  8]


In [37]:
arr= np.arange(2*3*4).reshape(2, 3, 4)
print(arr)
# Suppose we want to extract elements at positions:
# (0, 1, 2), (1, 2, 3)
i = np.array([0, 1])
j = np.array([1, 2])
k = np.array([2, 3])
ans = arr[i, j, k]
print(ans)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 6 23]


In [38]:
# Q34
arr = np.array([3, 7, 10, 2, 8, 1, 9])
ans = arr[(arr > 5) & (arr < 9)]
print(ans)

[7 8]


In [39]:
# Q35
arr = np.array([[1, 4, 7],[ 12, 24, 36 ],[51, 54 , 57]])
# Elements at (0,2), (1,0), (2,1)
row_idx = np.array([0, 1, 2])
col_idx = np.array([2, 0, 1])
ans= arr[row_idx, col_idx]
print(ans)

[ 7 12 54]


In [40]:
# Q36
arr = np.array([[1, 2], [3, 4]])
result = arr + 5
print(result)

[[6 7]
 [8 9]]


In [41]:
# Q37
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9,10,11,12]])
scale = np.array([[1], [2], [3]]) 
result = arr * scale
print(result)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


In [42]:
# Q38
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10,11,12]]) 
row_add = np.array([[10, 20, 30]]) 
result = arr + row_add
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


In [43]:
# Q39
a = np.array([[1], [2], [3]])
b = np.array([[10, 20, 30]])  
result = a + b 
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [45]:
# Q40
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

result = np.dot(a,b)
print(result)

[[22 28]
 [49 64]]


In [46]:
# Q41
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
result = np.mean(arr, axis=0)
print(result)

[2.5 3.5 4.5]


In [47]:
# Q42
arr = np.array([[1, 7, 3],
                [4, 5, 9]])
result = np.max(arr, axis=1)
print(result)

[7 9]


In [48]:
# Q43
arr = np.array([[1, 7, 3],
                [4, 5, 9]])
result = np.argmax(arr, axis=0)
print(result)

[1 0 1]


In [49]:
# Q44
def moving_sum(row):
    return np.convolve(row, np.ones(2, dtype=int), 'valid')
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
result = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print(result)

[[ 3  5  7]
 [11 13 15]]


In [52]:
# Q45
arr = np.array([[2, 4, 6],
                [8, 10, 12]])
result = np.all(arr % 2 == 0 , axis = 0)
print(result)

[ True  True  True]


In [56]:
# Q46
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [57]:
# Q47
matrix = np.array([[1, 2], [3, 4]])
flattened = matrix.flatten()
print(flattened)

[1 2 3 4]


In [58]:
# Q48
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.concatenate((a, b), axis=0) 
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [59]:
# Q49
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
result = np.split(arr, 2, axis=1)
print(result)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [60]:
# Q50
arr = np.array([10, 20, 30, 40])
inserted = np.insert(arr, 2, 25)  
deleted = np.delete(arr, 1) 
print("Inserted:", inserted)
print("Deleted:", deleted)

Inserted: [10 20 25 30 40]
Deleted: [10 30 40]


In [61]:
# Q51
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b
print(result)

[5 7 9]


In [62]:
# Q52
arr1 = np.array([5, 7, 9])
arr2 = np.array([1, 2, 3])
result = arr1 - arr2
print(result)

[4 5 6]


In [63]:
# Q53
result = arr1 * arr2
print(result)

[ 5 14 27]


In [64]:
# Q54
result = arr1 / arr2
print(result)

[5.  3.5 3. ]


In [65]:
# Q55
result = arr1 ** arr2
print(result)

[  5  49 729]


In [66]:
# Q56
arr = np.array(['apple pie', 'banana pie', 'cherry pie'])
count = np.char.count(arr, 'pie')
print(count)

[1 1 1]


In [67]:
# Q57
arr = np.array(['Hello', 'WorLD', 'PyTHon'])
upper_chars = [''.join([ch for ch in word if ch.isupper()]) for word in arr]
print(upper_chars)

['H', 'WLD', 'PTH']


In [68]:
# Q58
arr = np.array(['apple pie', 'banana pie', 'cherry pie'])
replaced = np.char.replace(arr, 'pie', 'tart')
print(replaced)

['apple tart' 'banana tart' 'cherry tart']


In [69]:
# Q59
a = np.array(['Good', 'Nice'])
b = np.array([' Morning', ' Job'])
result = np.char.add(a, b)
print(result)

['Good Morning' 'Nice Job']


In [74]:
# Q60
arr = np.array(['apple', 'banana', 'cherry'])
lengths = np.char.str_len(arr)
maxl = np.max(lengths)
print(maxl)

6


In [75]:
# Q61
arr = np.random.randint(1, 1001, 100)
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Std Dev:", np.std(arr))

Mean: 531.28
Median: 545.0
Variance: 79109.3416
Std Dev: 281.2638291711183


In [76]:
# Q62

arr = np.random.randint(1, 101, 50)
p25 = np.percentile(arr, 25)
p75 = np.percentile(arr, 75)
print("25th Percentile:", p25)
print("75th Percentile:", p75)

25th Percentile: 20.5
75th Percentile: 72.0


In [77]:
# Q63
a = np.random.randint(1, 50, 10)
b = np.random.randint(1, 50, 10)
corr = np.corrcoef(a, b)
print(corr)

[[ 1.         -0.09359027]
 [-0.09359027  1.        ]]


In [78]:
# Q64
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
print(result)

[[19 22]
 [43 50]]


In [79]:
# Q65
arr = np.random.randint(1, 100, 50)
p10 = np.percentile(arr, 10)
p50 = np.percentile(arr, 50)
p90 = np.percentile(arr, 90)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)
print("10th:", p10, "50th:", p50, "90th:", p90)
print("Q1:", q1, "Q3:", q3)

10th: 14.9 50th: 57.0 90th: 90.5
Q1: 32.5 Q3: 79.75


In [80]:
# Q66
arr = np.array([10, 20, 30, 40])
index = np.where(arr == 30)
print(index)

(array([2], dtype=int64),)


In [81]:
# Q67
arr = np.random.randint(1, 100, 10)
sorted_arr = np.sort(arr)
print(sorted_arr)

[ 1 23 26 31 38 42 46 54 61 74]


In [82]:
# Q68
arr = np.array([5, 23, 15, 42, 8])
filtered = arr[arr > 20]
print(filtered)


[23 42]


In [83]:
# Q69
arr = np.arange(1, 30)
filtered = arr[arr % 3 == 0]
print(filtered)

[ 3  6  9 12 15 18 21 24 27]


In [84]:
# Q70
arr = np.arange(10, 51)
filtered = arr[(arr >= 20) & (arr <= 40)]
print(filtered)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [85]:
# Q71
arr = np.array([1, 2, 3], dtype=np.int16)
print(arr.dtype.byteorder)

=


In [87]:
# Q72
arr = np.array([1, 256, 65536], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)

[16777216    65536      256]
